### PR TITLE
A big refactor with fixes and features

### PR DESCRIPTION
**Pull request by danreeves**
Note, if you want to use this you can `pip install -U git+https://github.com/danreeves/wagtailgmaps@3.0.0` or fork [danreeves/wagtailgmaps@3.0.0](https://github.com/danreeves/wagtailgmaps/tree/3.0.0)

---

Hi all,

I've just done a big refactor which I think simplifies the usage while making things more explicit and configurable. It also includes other fixes, like supporting the Google Maps API key.

Thought you might want to take a look.

Cheers

Edit: not sure why I made it 3.0.0, must have misread the current version.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by danreeves** [comment]
@SalahAdDin I did. I'll probably pull those `static()` calls into this PR. This PR is a pretty big refactor and so not really compatible with other PRs.

**Comment by SalahAdDin** [comment]
Oh, then, please pr.

**Comment by SalahAdDin** [comment]
@cavb t Where could we have a new release?

**Comment by SalahAdDin** [comment]
@springloaddeploybot Hey!

**Comment by danreeves** [comment]
@SalahAdDin 

In case you don't know, you can use `git+git://github.com/danreeves/wagtailgmaps.git@3.0.1#egg=wagtailgmaps==3.0.1` in your `requirements.txt`. That's how I'm doing it currently 😁

**Comment by SalahAdDin** [comment]
I can say it! Yes! You pull request is Pure GOLD!
But, something is missing, display the map in the django template, in the same way that Wagtail Admin.

**Comment by SalahAdDin** [comment]
And, man, second needed Feature! A StreamField block. I don't know where begins, if you want i can help you!

**Comment by SalahAdDin** [comment]
And add api files is needed also.

**Comment by SalahAdDin** [comment]
@danreeves 
I make a template tag for load `google-maps` API using the same `wagtail-hooks` code.
But, i don't know how render in the main templates, i tried creating a template tag like `django-embed-videos`, but is hard.

**Comment by SalahAdDin** [comment]
@danreeves Did you see this [repo](https://github.com/Frojd/wagtail-geo-widget). Is very interesting, but his kind of work is cross about this repository, it doesn't use address for work, use localization.

We can mix this  repository and make a more strong package, isn't it?

**Comment by SalahAdDin** [comment]
@danreeves Man, see [this](https://github.com/Frojd/wagtail-geo-widget/commit/cf573c4bec897311fffc0144719b520eb15b7d9b), is very good.

**Comment by danreeves** [comment]
@SalahAdDin Thanks! I'll check it out

**Comment by thibaudcolas** [comment]
Hey @danreeves, @SalahAdDin – I wasn't watching this repo (not sure who is) so only noticing the PR backlog now, sorry about that.

As you can see this package hasn't moved in a while – @danreeves I see we've merged one of your PRs in the past, would you be willing to be given write access to this project? We'd still require PR reviews, but it would be easier to release those changes.

I'll also try to find someone to review all of this.

**Comment by danreeves** [comment]
Yeah I'd be up for that; we use this project pretty frequently at work.

I'd be interested in any feedback, even if you don't want to merge! 

Thanks

**Comment by loicteixeira** [comment]
Superseded by #16.

**Comment by loicteixeira** [comment]
Ah.. The source repository for #16 was deleted so we can't use that. Reopening this PR then.

**Comment by loicteixeira** [comment]
Not overwriting Wagtail base templates and properly using the hooks so `django-overextends` isn't needed, not to mention the new panel. This is some great work. Thank you for your contribution 💯 

I'll have a look early next week to properly define which versions of Python/Django/Wagtail we want to support, maybe add some test 😱 and release a new version.

Can I ask why jump to `3.0` rather than `0.3`?

**Comment by danreeves** [comment]
Thanks for merging! The version was a typo, but maybe it should be a major bump anyway.

**Comment by loicteixeira** [comment]
It probably would if we had already reached `1.x` but since we're still on `0.x`, I don't think this is required.

In addition, I'm just picking up on this package and would like to use it a bit myself to see if there's improvements/changes to be made before we reach "stable".

**Pull request merged**
