### PR TITLE
Adds support for Google Maps API keys

### LINKED ISSUE #11: New projects require API keys
As of June 22nd, new google maps projects require an API key with Google Maps Geocoding API enabled.

Info: https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

PR: #12

### PR DESCRIPTION
**Pull request by danreeves**
Fixes #11

API keys are required for new projects: https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

Let me know what you think

### CODE REVIEW

**Comment by danreeves** [comment]
Actually I'm getting a 404 on `http://localhost/assets/wagtailadmin/css/admin.css` which is coming from here: https://github.com/springload/wagtailgmaps/blob/master/wagtailgmaps/wagtail_hooks.py#L29

**Comment by craigloftus** [comment]
Wagtail 1.5 now provides an `insert_global_admin_js` hook to achieve what `overextends` is being used for here. I can make a PR for that, but it is probably only worth doing if you're willing to break compatibility with older Wagtail projects?

@danreeves I don't see that the 404 is related to your PR? See https://github.com/springload/wagtailgmaps/pull/14

**Comment by craigloftus** [comment]
@danreeves I've just tested this branch with Django 1.9 and it doesn't work because `simple_tag` now escapes by default. I'd suggest using an `inclusion_tag` instead, with a one line partial template, which should behave correctly across versions and also provides users a little more flexibility.

**Comment by SalahAdDin** [comment]
Any news about this?

**Comment by loicteixeira** [comment]
Thank you for your contribution. Sorry it took so long to merge. It seems that nobody was watching this repository.

**Pull request merged**
